### PR TITLE
Moved All Core stuff  to Core/ 

### PR DESCRIPTION
**Pull request by BEASTSM96**
- Core.h-> Core/Base.h
-  Log -> Core/Log.h
- Added PlatformDetection

### CODE REVIEW

**Comment by sfulham** [comment]
What's the point in having the PlatformDetection header? It doesn't need to be in a separate file.

**Comment by BEASTSM96** [comment]
Just for the future; it could get bigger

**Comment by sfulham** [comment]
So? That doesn't matter.

**Comment by MarcasRealAccount** [comment]
Depends on the file structure, but imo it should just stay in Core.h

**Comment by sfulham** [comment]
I'm going to close this as 1. We haven't decided on file structure yet 2. Having platform detection in a separate file is unneccesary.

**Pull request closed without merging**
