### PR TITLE
Fix compiler errors

### PR DESCRIPTION
**Pull request by dr01d3k4**
Moves event header files to include folder an adds missing include to fix compilation errors.

### CODE REVIEW

**Review by sfulham — DISMISSED** [review]
Event.h isn't required to be included in EventHandler because Event isn't actually referenced anywhere in there.

**Comment by MarcasRealAccount** [comment]
sfulham, if you don't include Event.h in EventHandler.h it doesn't compile, because Event is referenced on line 21 as ```Event&```.
But this pull request wasn't necessery as I did this in my pull request.

**Comment by sfulham** [comment]
Oh yeah, didn't see that, sorry.

**Comment by sfulham** [comment]
You will need to rebase though

**Pull request merged**
