### PR TITLE
Input Binding system & Configuration System

### PR DESCRIPTION
**Pull request by MarcasRealAccount**
### The Input Binding System
This system allows making input settings, and with the help of the Configuration system it can save/load the settings, so that they don't have to be rebinded every time the game launches.
This system also allows for grouped inputs, this means it is possible to have multiple groups of inputs where only one of those groups can be active at a time, allowing a system like in No Mans Sky input settings.
The system also uses std::function for the callbacks, making it possible to have member functions be callbacks 😄
### The Configuration System
This system is currently pretty basic with the current format being `<id>=<value>\n`.
This system can be expanded in the future if need be, as long as the overall structure stays the same.
### Note
Had to move sfulham's event system headers to the include folder.

### CODE REVIEW

**Review by sfulham — COMMENTED** [review]
I honestly don't think we need this because there's no problem in configuring events at runtime

**Comment by MarcasRealAccount** [comment]
Could you be more specific with "there's no problem in configuring events at runtime"?

**Comment by sfulham** [comment]
Well, there's no need for this PR, it just adds unneccessary code imo, there's no real difference between using this or not

**Comment by sfulham** [comment]
[Event Binding and Config](https://trello.com/c/PMbmZK7a/21-event-binding-and-config)

**Comment by sfulham** [comment]
[Event Binding and Config](https://trello.com/c/PMbmZK7a/21-event-binding-and-config)

**Comment by MarcasRealAccount** [comment]
Maybe there should be a poll about this?

**Comment by Gaztin** [comment]
I'd love to see some example use cases for this. It's a lot of code to digest! But to me it sounds useful. Not sure why @sfulham is so against it. Maybe they can elaborate?

**Comment by sfulham** [comment]
Yeah, I'd like to see some example use cases but I just don't understand why we would need this.

**Comment by MarcasRealAccount** [comment]
I added some example use cases in the main.cpp file, to test the system whilst I was making it,
It's under the comment where I said I made a big mess xD

**Comment by Gaztin** [comment]
> 
> 
> Yeah, I'd like to see some example use cases but I just don't understand why we would need this.

Eventually we are going to have to deal with input stacks and actions. Maybe it's a smudge over-engineered, but it does the job. Imagine if we are going to be able to open up a pause menu when we press ESCAPE. But maybe we want some kind of state machine where ESCAPE also is bound to cancel our inventory screen or something like that. I assume this is going to help with that kind of stuff.

**Comment by MarcasRealAccount** [comment]
Yup, that is what it was made to do :)

**Comment by sfulham** [comment]
> > Yeah, I'd like to see some example use cases but I just don't understand why we would need this.
> 
> Eventually we are going to have to deal with input stacks and actions. Maybe it's a smudge over-engineered, but it does the job. Imagine if we are going to be able to open up a pause menu when we press ESCAPE. But maybe we want some kind of state machine where ESCAPE also is bound to cancel our inventory screen or something like that. I assume this is going to help with that kind of stuff.

Well, yeah, it is definitely overengineered, like the whole writing it to files, and we can already do this sort of stuff without it, some of this stuff is what the EventHandler class was made to do.

**Comment by MarcasRealAccount** [comment]
I made it so that any time when the project needs a new input its as simple as calling at a minimum of one function, and then it just works.
So that it wouldn't require one person who knows how the input system works from the ground up to add one new input.

**Comment by sfulham** [comment]
Well, tbh, the event system isn't that big nor confusing so learning how to use it really isn't a problem

**Comment by MarcasRealAccount** [comment]
I know that the event system isn't big, but take this as an example:
If the game has a menu that is opened with escape, then every place where the keybinds are handled would have to check if the menu is open or not, but with the system I created here, all those places would only have to execute a function to first get or create an input group, then create the binding necessary, and then whenever the correct event passes through the InputHandler it will execute the callback, and it also makes it easy to change what button, axis, or whatever it should listen to without altering the source code.

Granted the code is a bit big (in that it has a bit of files), but in the end it makes the process of adding inputs literally pain free, as you dont have to create the input bindings at one specific location as long as that location has access to an InputHandler, which could be made into a static class

But since you are so keen on using the event system on its own. I guess I will just put this into its own branch until you figure out that the event system would make more pain than this "finished" system, but I cant do it until I get up in roughly 7-9 hours

**Comment by dr01d3k4** [comment]
I think your input binding objects should pretty simple PODs. They shouldn't need to worry about saving/loading - another system should handle that.



On the topic of input handling, for gameplay do we want to use polling or events? I've typically used a polling based design like this:
Have an enum for all the different controls that can be bound:
```
enum Action
{
	Up, Down, Left, Right,
	Jump, Shoot, Pause,
	// etc.
	Count
};
```
And a ControlBinding class that stores the binding:
```
struct ControlBinding
{
	std::string primaryKey;
	std::string secondaryKey;
	int gamepadAxis;
	int gamepadButton;
	// Probably a cleaner way to do this
};
```

Then associate an action with a binding:
```
struct ControlMap
{
	ControlBinding bindings[Action::COUNT];
};
```

And an InputController:
```
class InputController
{
public:
	float getStateForAction(Action action);
private:
	ControlMap m_controlMap;
	Keyboard* m_keyboard;
	Gamepad* m_gamepad;
}
```
`getStateForAction()` returns a float between 0 and 1. A keyboard binding is either 0 for not pressed or 1 for pressed. A gamepad binding could be any value due to analogue sticks/triggers. Allows us to do something like `float dx = inputController.getStateForAction(Action::Right) - inputController.getStateForAction(Action::Left); player.position.x += dx * speed;`

Finally, in an ECS based design, we can create a component to store our InputController:
```
struct PlayerInputComponent
{
	InputController inputController;	
}
```

By creating 2 instances of InputController with a different ControlMaps (and e.g. gamepad pointer), we can then easily get local multiplayer support.

**Comment by MarcasRealAccount** [comment]
The input system I created here uses the configuration system I also created here to save/load the bindings.

It seems we are using an event based system, thats what this is supposed to extend on.

**Review by sfulham — CHANGES_REQUESTED** [review]
I reckon the save/load stuff is just overengineering this, its very unneccessary and it makes it harder for people to understand the system.

**Comment by dr01d3k4** [comment]
Yeah, but I don't think the input system should know about the configuration system. Some other layer should exist that loads the configuration to instantiate the IInputBindings.

**Comment by MarcasRealAccount** [comment]
So you are proposing that I remove the ability to change input bindings in a settings menu. Basically what you're saying is that the input system doesnt need the most usual system known to games. Like how else would you make it able to do the easy task of settings?

The instantiation can be done anywhere as long as you have an instance to a InputHandler.

So this is how the system works:
First you create an InputHandler
Then you create an InputGroup* by executing InputHandler.CreateInputGroup("someId")
Then to create a key input binding you call InputGroup.CreateButtonImputGroup("someId", InputLocation::KEYBOARD, ButtonInputType::PRESS, keycode, std::bind(&someCallback, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3))

Idk if the functions have been written correctly as I don't have the code infront of me right now.

For now since the event system hasn't been fully implemented yet. You can pass some custom events to the InputHandler.HandleEvent(event) function.
There is a working example of the system in the main.cpp file.
The configuration system creates a file in "src/game/assets/configs/inputBindings.conf" where you can alter the index for the binding to whatever you want and then the next time the game launches and creates the inputs it will take from the config file instead of the passed values to the create function.

**Comment by dr01d3k4** [comment]
Input bindings should definitely be saveable and loadable, but the input bindings **themselves** shouldn't know about that system. How about a `class InputManager { public: IInputBinding* createBinding(...); };` that deals with opening the configuration file and reading settings from it. IInputBinding's constructor would then just take in location and index data from the input manager. You could then add an InputManager* to the bindings themselves, so that in something like `IInputBinding::SetBinding(...)`, you can call `m_inputManager->setBinding(...);`, which then sends it on to the configuration.

**Comment by MarcasRealAccount** [comment]
I could move the config loading into the InputGroup class instead. If that helps, making the IInputBinding have no knowledge of the config system

**Comment by MarcasRealAccount** [comment]
Ok I made the changes that dr01d3k4 what speaking of.
But I still don't fully understand why you don't want the ability to save/load inputs.

**Review by sfulham — APPROVED** [review]
I'm just gonna go ahead and aprove this because while, yes, I think its too early to implement this, we may need it in the future

**Pull request merged**
