### PR TITLE
New Config System and Renderer

### PR DESCRIPTION
**Pull request by MarcasRealAccount**
# New Config System
The new config system has been renamed to `Config` instead of `Configuration` as it was too long imo.
It has also been moved into `gp1::config` namespace instead of `gp1::configuration` as it was also too long imo.
And it should work with `.ini` files instead of `.conf` with custom style.

Currently the system supports:
- Sections.
- Nested sections.
- Multi line. (Though I'm not confident it will work all the time, so please refrain from using it)

It also has new functions that convert the `string` value to an `int64_t`, `uint64_t` or `bool` if that is needed.
Some of the functions was removed or renamed.
There's now a function to get all the configs or sections inside a section.

# Renderer
The renderer currently supports meshes and materials.
To render a mesh use `RenderMesh(OpenGLMeshData* mesh)`
To render a mesh with a material use `RenderMeshWithMaterial(OpenGLMeshData* mesh, OpenGLMaterialData* material)`

There are currently 3 mesh types:
- Static Mesh (Holds position, normal, and uv)
- Static Voxel Mesh (Holds position, normal, uv and SSBO index)
- Skeletal Mesh (Holds position, normal, uv, joint indices and joint weights)
If a mesh's `m_Editable` variable is true you can call `MarkDirty()` on the mesh after changing the vertices, that will cause the renderer to recreate the gl data the next time it is rendered.

There is also a Shader class that handles a shader.
To get a shader use `Shader::GetShader(std::string id)`

There is a Material class that handles material related stuff like uniforms.
To get a uniform use `GetUniform<T>(std::string id)`, this function will try to get a uniform with the given type and id.

The uniform system is pretty robust, and is easy to extend with more stuff like textures (By that I mean there isn't texture support yet, so please add that for me 😜)
Currently the list is:
- float
- vec2
- vec3
- vec4
- int
- ivec2
- ivec3
- ivec4
- uint
- uvec2
- uvec3
- uvec4
- mat2
- mat3
- mat4

### CODE REVIEW

**Comment by Gaztin** [comment]
Cool! The amount of string copying worries me a little bit. Try and clean up and use `std::string_view` where you don't need to store the string argument, and please use `std::move` when you do, so we can minimize the amount of copies.

**Comment by MarcasRealAccount** [comment]
Yeah I came across a problem trying to make the uniforms templated,
For the material to be able to set the uniforms, it needs to store the uniforms, but how would it be possible to store templated uniform pointers?

**Comment by Gaztin** [comment]
Can it simply store a `T m_Value` ?

**Comment by MarcasRealAccount** [comment]
Yeah that one is fine, but storing the `Uniform<T>` in a way to be able to upload the uniform value to the gpu is not easy.
Though I found `std::any` and I will try to use it first before saying it's impossible.

**Comment by MarcasRealAccount** [comment]
Ok I got the uniforms to be templated, though the code is pretty messy (so please go through the `Material.cpp` file and tell me what should be done differently).
I literally have no idea how it works, it just does.

**Comment by Gaztin** [comment]
[Renderer](https://trello.com/c/5XLm7Wbo/15-renderer)

**Review by sfulham — APPROVED** [review]
This looks OK to me

**Pull request merged**
