### PR TITLE
New Renderer interface and OpenGL 4.3 renderer

### PR DESCRIPTION
**Pull request by MarcasRealAccount**
# What this implements
This PR will implement a new interface for the renderers, and a storage for the compiled graphics apis.

Most of the changes are in `include/Engine/Renderer` and `src/Engine/Renderer`

# Renderer interface
This interface currently has:
* Abstract **`gp1::renderer::RendererData`**
* Abstract **`gp1::renderer::DynamicRendererData`** extends **`gp1::renderer::RendererData`** adds m_Dirty, m_Editable and m_Dynamic variables.
* Abstract **`gp1::renderer::Mesh`** extends **`gp1::renderer::DynamicRendererData`**
* **`gp1::renderer::StaticMesh`** extends **`gp1::renderer::Mesh`**
* Abstract **`gp1::renderer::Texture`** extends **`gp1::renderer::DynamicRendererData`**
* **`gp1::renderer::Texture2D`** extends **`gp1::renderer::Texture`**
* **`gp1::renderer::Texture2DArray`** extends **`gp1::renderer::Texture`**
* **`gp1::renderer::Texture3D`** extends **`gp1::renderer::Texture`**
* **`gp1::renderer::TextureCubeMap`** extends **`gp1::renderer::Texture`**
* **`gp1::renderer::Shader`**
* **`gp1::renderer::ShaderProgram`** extends **`gp1::renderer::DynamicRendererData`**
* **`gp1::renderer::Material`** extends **`gp1::renderer::RendererData`**
* **`gp1::renderer::ReservedUniformBuffers`** extends **`gp1::renderer::RendererData`**
* Abstract **`gp1::renderer::Uniform`** extends **`gp1::renderer::DynamicRendererData`**
* **`gp1::renderer::Uniform[Type]`** extends **`gp1::renderer::Uniform`** where `[Type]` is one of the names in the enum **`gp1::renderer::EUniformType`**, but the vector and matrix types have their underlying data type shrunk to one character.
* **`gp1::renderer::UniformBuffer`** extends **`gp1::renderer::RendererData`**
* Abstract **`gp1::renderer::DebugRenderer`**
* Abstract **`gp1::renderer::Renderer`**

The function **`[TypeName]::Create();`** where `[TypeName]` is the name of the type without `[` or `]` is used to create a new instance of the type extending **`gp1::renderer::RendererData`** excluding **`gp1::renderer::DynamicRendererData`** but including those extending it, optionally you can also use the function **`gp1::renderer::Renderer::Create[TypeName]();`**, but it is not recommended.

So to create a **`gp1::renderer::StaticMesh`** you would call `gp1::renderer::StaticMesh::Create();` and for OpenGL it would return a new instance of **`gp1::renderer::opengl::OpenGLStaticMesh`**.

The function **`gp1::renderer::Renderer::IsCompatible();`** can be used to check if the renderer is compatible on the current system.

This interface as seen uses inheritance to implement per graphics api functions and variables, thus it should not require **`RTTI`** to work.

**`gp1::renderer::ReservedUniformBuffers`** is used to store global uniforms like the camera's matrices.

# Graphics API storage
The class **`gp1::renderer::Renderers`** is used to store graphics apis at the start of the application.
And to retrieve and construct one of the renderers you can call one of the following:
* **`s_Renderers->GetBestRenderer();`** This gets the best compatible renderer using each entry's priority from high to low and using the **`IsCompatible();`** function of the renderers.
* **`s_Renderers->GetRenderer(const std::string&);`** This gets the renderer of the given name.

# Application
I have added the ability to set the renderer to use from an `.ini` file located in `Config/Application.ini` from the run path.
```ini
[Renderer]
Selected = best
```
the options are "best" for the best compatible renderer and the names of the renderers listed below.

This is the list of the current renderers:
API: Name, Priority
* **OpenGL**: **`"opengl"`**, **`0`**
* **Vulkan**: **`"vulkan"`**, **`1`**

### CODE REVIEW

**Comment by anguslmm** [comment]
Still reviewing most of the code, but question for you: Why the use of `shared_ptr` everywhere? That can be a bit dangerous as it can hide bugs where we operate on an object's member after the object has been destroyed without realizing it.

In general, cases where a class member should be a `shared_ptr` are rare. If you have a bunch of objects that all need access to some resource, and you want that resource to be destroyed when the last of those objects is destroyed, then it makes sense. Otherwise, the object that controls the lifetime of the object should have a `unique_ptr`, and objects that just need a reference to it can either access it from the owning object, or store it as a raw pointer.

**Comment by MarcasRealAccount** [comment]
How can `shared_ptr` be dangerous when you can't get a `shared_ptr` to a destroyed object when using it in a normal manner, i.e. not using the `.get()` function.
But in general I wanted to test it against other ways, so therefore they might all become regular pointers after I test it's performance compared to `shared_ptr`.

**Comment by anguslmm** [comment]
That's exactly why `shared_ptr` is dangerous. It hides bugs. If we're accessing something after it should've been destroyed, we won't know. That's a problem. We WANT things to crash if we try to access a destroyed object. That means there's a fundamental problem in our code. If a class's member should be destroyed when it is destroyed, it should be a `unique_ptr`.

**Comment by anguslmm** [comment]
This PR looks like a solid starting point besides the above issue.

**Comment by MarcasRealAccount** [comment]
I haven't had much time to do any work, I have been doing other stuff for a bit.
But now I'll try to remove all `std::shared_ptr`s and convert them to raw pointers.
Maybe I will do what you told me with using `std::unique_ptr`s and just passing around raw pointers everywhere, but idk.

**Comment by anguslmm** [comment]
Sure thing, not trying to say there can be no `std::shared_ptr`s, just make sure that the ptr type we're using makes sense with the lifetime and ownership we're looking for.

**Comment by matty2048** [comment]
Yeah, meshes should probably be shared_ptr as it'll make it much easier to cache and reuse them.

**Comment by MarcasRealAccount** [comment]
Yeah that's why I sorta tried out `std::shared_ptr`s so I wouldn't have to deal with their lifetime and ownership, but there's obviously some problems with them.
So I say I'll see what the fps gain would be with 10000 textured spinning quads rendered separately using raw pointers and if it's small like below a few milliseconds I would say that using those `std::shared_ptr`s would be fine as long as people don't store `std::shared_ptr`s in classes/structs that only need to know they might exist (use `std::weak_ptr` in those cases) and that we don't make cyclic dependencies with `std::shared_ptr`s which are always bad.

```
Windows Release mode 10000 textured spinning quads:
std::shared_ptr: ~36.2ms render latency
smart_pointers::shared_ptr: ~36.3ms render latency
```
Here's a reference of what the render latencies currently are. (`smart_pointers::shared_ptr` was my own attempt at a non thread safe shared_ptr type)

**Comment by anguslmm** [comment]
My concern has nothing to do with performance. It’s about lifetime and
hiding errors.

If we want to use shared_ptr by default and just be very tight about taking
weak_ptrs when appropriate, that works too.

**Comment by MarcasRealAccount** [comment]
I should say that the `std::shared_ptr`s owners are the caller.
So for instance calling `gp1::renderer::StaticMesh::Create();` will obviously create a new `StaticMesh` but the caller is now the owner of that static mesh, and the renderer only stores a `std::weak_ptr` to it so it knows it's been created by the renderer and knows that it might exist.
Also when creating a new entity and attaching it to a scene, the caller of those functions has full ownership of them, so this means that it's up to the caller when the entity should get removed from the scene (which happens automatically the next time `Update()` is called on the scene).
But I can obviously see that the entity wouldn't get removed from the scene until all `std::shared_ptr`s to it are destroyed, but that could be fixed at some other point in time.

**Comment by MarcasRealAccount** [comment]
Update: After battling access violations and stuff not loading properly it works. The downside is that the fps didn't increase whatsoever in release mode (debug mode got increased by 20 fps lol), so should I change the `std::shared_ptr`s in the renderer branch, or should we just stay with `std::shared_ptr`s until they really make problems.

**Comment by anguslmm** [comment]
Again, this was not about performance at all, although `shared_ptr` can have significant performance implications. It's about safety and ownership. The two most popular C++ style guides on this subject:

- [R20 and R21 of the ISO C++ Style Guide](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-owner)
- [Ownership and Smart Pointers in the Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Ownership_and_Smart_Pointers)

This is because `shared_ptr`, when misused, quickly becomes a hidden global variable. This makes things difficult to reason about and bugs difficult to diagnose. Using `shared_ptr` does NOT mean, "I'm going to use this in more than one place," but instead, "I want this resource to be destroyed precisely when all of these scopes that accessed it end." Using `shared_ptr` when you don't intend to have actual shared ownership of an object and its lifetime is wrong and bad, period. The idea that you should never use raw pointers is taking the wrong lesson from modern C++ and smart pointers. This is a particularly egregious case, because most of the resources that are `shared_ptr`s here aren't even being mutated, meaning they could just be `const T*`s.

Everything I've said above, however, doesn't matter if there's just a reason I'm not seeing that every entity that reads a mesh needs mutate access and control of its lifetime, for example. Wouldn't it make more sense to have a separate class that owns the mesh, so that every object that needs read access to a particular mesh can simply get a `const Mesh*` to it, and we can have direct and explicit control over the resource's lifetime?

All that said, it looks like I'm not convincing anyone here. So while I maintain that the above is important and accurate, I get that this is a blocker and things need to keep moving. So if a third party says this looks good, then I'll merge it and we can use it as a starting point.

**Comment by MarcasRealAccount** [comment]
Alright give me a few days so I can change them to `std::unique_ptr`s and make it remove itself from the areas where I've used `std::weak_ptr`s to indicate that the object might exist.

**Comment by anguslmm** [comment]
To be clear, if there's a place where you're sure `shared_ptr` makes sense and I'm not seeing it, please don't change that, just explain. I'm not saying never use `shared_ptr`, just that `unique_ptr` should be the default unless shared ownership is truly needed.

**Comment by MarcasRealAccount** [comment]
Here we go if you see anything you want changed just tell me :)

**Review by anguslmm — APPROVED** [review]
I appreciate you going through the work to do that. It should save us headaches later!

**Comment by anguslmm** [comment]
In the interest of keeping things moving, I'm going to avoid nit picking on this PR any more since it's a big one and lots of work is dependent on this. Overall things look good, so we'll deal with any issues in future PRs.

**Pull request merged**
